### ISSUE TITLE
Adaptive Fog does not work with MartyMcFly RT shader because of reversed depth input.

### ISSUE THREAD

**Issue by asasyn134** [FransBouma/OtisFX#10]
Hello,

I'm playing Witcher 1 right now and iv got Marty McFly shader to work by setting RESHADE_DEPTH_INPUT_IS_REVERSED to 1.

However, AdaptiveFog works only when RESHADE_DEPTH_INPUT_IS_REVERSED is set to 0.

Is there a way to make the fog work in such setup?

Best Regards

**Comment by FransBouma** [comment]
adaptive fog uses the linearized depth buffer of reshade, so it shouldn't matter if reversed is set to 1 or 0. You use a recent version?

**Comment by asasyn134** [comment]
Yes, I've downloaded it again to double-check.

It is weird. When RESHADE_DEPTH_INPUT_IS_REVERSED is set to 1 only RTGI shader works but other depth-based shaders do not.

When DisplayDepth.fx effect is activated it only shows depth when RESHADE_DEPTH_INPUT_IS_REVERSED=0, but to make RTGI work I need to set it to 1 and then DisplayDepth.fx shows a black screen,

I hope that explanation will help You grasp the issue.

**Comment by FransBouma** [comment]
DisplayDepth has its own variables for reversed, you have to explicitly enable you'll use the global vars in display depth. 
I don't know the RTGI shader, perhaps it has its own variables for linearization of the depth buffer. All I can say is that adaptive fog uses the reshade global variables like other depth based shaders do too. It might very well be Marty implemented his own linearization to be sure things work as intended.

**Comment by asasyn134** [comment]
I have set DisplayDepth to use global settings.

**Comment by FransBouma** [comment]
ok, so all shaders work when reversed is 0 but displaydepth shows a black screen? That doesn't make sense. You're sure you've picked the right depth buffer in the dx11/12 tab ? In any case, if you have displaydepth set to use global vars and the global var set to 0 and you see a black screen but with 1 you see the right screen, something else is wrong, but I don't know what. I never have had this problem.

**Comment by asasyn134** [comment]
No, the other way around :) Everything works (including DisplayDepth) when reversed is set to 0.
Marty's shader works only when reversed set to 1, which is weird because DisplayDepth when set to 1 goes full black.

**Comment by FransBouma** [comment]
Ah, then I think it's something you should pick up with Marty, as I don't know what's wrong but it looks like it has something to do with his shader: everything else works fine with the 0 value. :)
