### ISSUE TITLE
Far plane max blur issue with performance mode turned on

### ISSUE THREAD

**Issue by Yundaz** [FransBouma/OtisFX#11]
Been using this with active gameplay. Far plane max blur is turned to 0.00 and near plane max blur 1.10     when swapping to performance mode in reshade the plane max blur is turned up all the way and objects in the distance are also blurry.

**Comment by FransBouma** [comment]
cinematic dof, latest version I presume? Reshade 4.9.1 ?

**Comment by Yundaz** [comment]
> 
> 
> cinematic dof, latest version I presume? Reshade 4.9.1 ?

Latest cinematic dof indeed, 4.8.2 currently, tested it with 4.9.1 same issue seems to occur in performance mode. Any clues? great shader by the way, best DOF out there imo

**Comment by FransBouma** [comment]
> Latest cinematic dof indeed, 4.8.2 currently, tested it with 4.9.1 same issue seems to occur in performance mode. Any clues? 

no, but I never run performance mode so I haven't ran into it. Will test it tomorrow.

> great shader by the way, best DOF out there imo

Thanks!

**Comment by FransBouma** [comment]
I can't reproduce it. Auto focus or manual focus, when I set up the dof parameters, and switch to performance mode, nothing changes in the image, it's using the same values, from what I can tell (values aren't visible in performance mode, but image stays teh same).

**Comment by Yundaz** [comment]
[Image1](https://imgur.com/a/qqfdTOE) Here is a screenshot of the settings I am currently using (unlocked version for depth access in online games)   Here is how it looks with performance mode turned on: [Image2](https://imgur.com/a/JFVWRJf)   Notice the depth in the background turning on as well now.

**Comment by FransBouma** [comment]
Is that standard reshade, or a wrapper? (like there are for specific games) ? I honestly don't know what's going on, as I can't reproduce it. It should work just fine with performance mode, I couldn't see any blurring in my testing in the far plane when I switched to performance mode. I've asked on the reshade discord if there's something with the performance mode I've overlooked, but to my knowledge it should work as-is...

**Comment by Yundaz** [comment]
Hmm it is indeed a wrapper of reshade, would you mind if I send you my setup ? How do I best reach out to you? via discord? Yundaz#4269

**Comment by FransBouma** [comment]
Sorry but I'm not going to debug someone's wrapper... they likely do something weird that's out of my control, so I can't change that... :) The shader itself works fine within reshade so if some wrapper creates issues, then perhaps not use the wrapper?
