### ISSUE TITLE
CinematicDoF / Emphasize no target plane

### ISSUE THREAD

**Issue by J-1775** [FransBouma/OtisFX#15]
Tried filters in **DCS** and **IL-2**. While they do work, they do not work as expected. 
Starting in default settings with auto-focus checked makes no difference: renders 100% sharp from fore- to background. Unckecking autofocus flashes an all over blue screen and then blurs the picture uniformely from fore- to background. 
Turning down 'manual focus plane' to 0.10 renders a sharp picture. Increasing the value blurs the picture **uniformly**. 
Checking 'CoC values and focus plane' gives a uniform picture of brown-red color. 
I suspect a problem with depth information?
I have latest versions of Reshade (DX9/11/12 install for both sims) and Nvidia drivers. I also tried Reshade 4.8.

**Comment by FransBouma** [comment]
Make sure the depth buffer is setup correctly. https://framedsc.com/ReshadeGuides/setupreshade.htm#checking-depth-buffer-access. If these are online games, there's no depth buffer access and all depth buffers will be empty and you get what you describe

**Comment by J-1775** [comment]
THANKS YOU SO MUCH Frans! That link (site hitherto unknown to me) helped me within a couple of minutes! Shame on me if I missed it in the docs resp. headers. 
Now I must go back and further explore your absolutely stunning filter!
