### ISSUE TITLE
i'cant focus manual on msf2020

### ISSUE THREAD

**Issue by mauristapich** [FransBouma/OtisFX#22]
Hi how are you? I couldn't focus manually with a shallow depth of field in the latest version, in the previous versions I could see some blue aids where it showed the area in focus, but not now. I set aperture, focal plane distance and focal length but I don't see changes, could you help me?
![12](https://user-images.githubusercontent.com/123178156/216072076-6a7a6e2b-340a-4f03-a280-516c3f777838.jpg)

**Comment by FransBouma** [comment]
Please setup the depth buffer correctly (https://framedsc.com/ReshadeGuides/setupreshade.htm#checking-depth-buffer-access) . I also remember it does have an online component, so it might be reshade doesn't enable the depth buffer. If the depth buffer isn't setup properly or not available, the dof doesn't work

**Comment by mauristapich** [comment]
Thanks! I'll try to read the tutorial when the reshade page responds. because the server is not working. Greetings FransBouma!
