### ISSUE TITLE
CinematicDOF.fx failed to compile error X4509

### ISSUE THREAD

**Issue by windbelle** [FransBouma/OtisFX#23]
Hello. I was having an issue with the latest release of CinematicDOF.fx being failed to compile in the game Sims 4, with the message of "error X4509: maximum sampler register index exceeded, target has 16 slots, manual bind to slot s16 failed". This issue persists with just the standard shader and otis_inf installed, from the ReShade library or directly from GitHub. The issue also occurs in ReShade 4.9 and 5.x, including the latest 5.6 ReShade version.

However converting back to OtisFX version 1.2.5 is okay :)

**Comment by FransBouma** [comment]
Hi,

Yes the recent update required more samplers and that causes dx10/9 not to work with it anymore. As these are really old and there's really not a fix, I went ahead and pushed the update. YOu can indeed go back to an older version, you only miss the shape addition for the bokeh, but that's about it.
