### ISSUE TITLE
Some effects not working?

### ISSUE THREAD

**Issue by Sway1309** [FransBouma/OtisFX#27]
Hello, 
sorry but I can't find anything to this theme - I had installed the master.zip and it is also displayed in home of reshade. But some effects like an example depthdarkness doesn't work. I despair.. I had tried out so much different things - but it's not working. 

![reshade](https://github.com/FransBouma/OtisFX/assets/147317150/658a85fc-8249-4ed2-af5c-2d4cb6cd3b55)

Greetings, Sway

**Comment by FransBouma** [comment]
https://framedsc.com/ReshadeGuides/setupreshade.htm#checking-depth-buffer-access
