### ISSUE TITLE
Can add autofocus sample radius?

### ISSUE THREAD

**Issue by slayermaster** [FransBouma/OtisFX#9]
Can you add autofocus sample radius, like the one in ADOF (qUINT) by Pascal?
Your DOF looks the best and is easily adjustable but the autofocus is really limited when I cant use mouse cursor to drive the focus.

**Comment by FransBouma** [comment]
Autofocus in my dof is really for gameplay, it picks the focus point on a single pixel indeed. averaging the depth over a couple of pixels is possible but frankly, if it is up to me I'd remove it altogether. 

Focusing for screenshots is done better with manual focusing or by moving the autofocus point with the values for it in the settings. 

What's your use case here exactly, could you elaborate on that a bit?

**Comment by slayermaster** [comment]
Oh I plan to use it on cutscenes, where the focus or character is usually in the middle of the frame, but sometimes they move to the sides so it'll focus the background instead. And third person games like Assasins' Creed 1, where mild DoF usually works well.

**Comment by FransBouma** [comment]
For shots I presume?

In that case, just use the `AutoFocusPoint` values. There are two values which dictate where the autofocus point is. When you check the checkbox `Show out-of-focus plane overlay on mouse down` you get a nice crosshair which precisely says where the focus point is. 

In case of live video, then there's little you can do, as the subject to focus on can be everywhere of course. So having a small circle around the focus point (which then still will be in the middle) will still miss it.

**Comment by slayermaster** [comment]
It's moving cutscene, for improved gameplay I guess. Old games cutscenes I've tested tend to have their focus in the center or a tad to the sides so that's what brought this requests. But I can live with current autofocus system, no problem.

**Comment by FransBouma** [comment]
Ok :) I'm not going to add what you want any time soon so I'll close this issue for now
